/*
# Momentum V1.5 Database Schema

## Overview
Complete database schema for the Momentum AI Co-Pilot app that handles goal tracking, 
AI-generated plans, and intelligent task management.

## New Tables
1. **profiles** - User profile data linked to Supabase auth
   - `id` (uuid, primary key, references auth.users)
   - `persona_preference` (text, default 'professional')
   - `created_at` (timestamptz)

2. **goals** - User goals with AI-generated plans
   - `id` (bigint, primary key)
   - `owner_id` (uuid, references auth.users)
   - `title` (text, goal title)
   - `user_inputs` (jsonb, questionnaire answers)
   - `full_ai_plan` (jsonb, complete AI-generated plan)
   - `duration_days` (int, planned duration)
   - `start_date` (date)
   - `end_date` (date, calculated)
   - `status` (text, goal status)
   - `created_at` (timestamptz)

3. **tasks** - Individual daily tasks from goals
   - `id` (bigint, primary key)
   - `goal_id` (bigint, references goals)
   - `owner_id` (uuid, references auth.users)
   - `description` (text, task description)
   - `day_number` (int, day in goal plan)
   - `scheduled_date` (date)
   - `duration_minutes` (int, estimated duration)
   - `is_completed` (boolean, completion status)
   - `status` (text, task status)
   - `created_at` (timestamptz)

## Security
- Enable RLS on all tables
- Add policies for authenticated users to access their own data
- Ensure data isolation between users
*/

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  persona_preference TEXT DEFAULT 'professional' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create goals table
CREATE TABLE IF NOT EXISTS goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  user_inputs JSONB DEFAULT '{}',
  full_ai_plan JSONB DEFAULT '{}',
  duration_days INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  status TEXT DEFAULT 'active' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id BIGINT REFERENCES goals(id) ON DELETE CASCADE NOT NULL,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  description TEXT NOT NULL,
  day_number INT NOT NULL,
  scheduled_date DATE,
  duration_minutes INT DEFAULT 30,
  is_completed BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for profiles
CREATE POLICY "Users can read own profile"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- Create RLS policies for goals
CREATE POLICY "Users can read own goals"
  ON goals
  FOR SELECT
  TO authenticated
  USING (auth.uid() = owner_id);

CREATE POLICY "Users can create own goals"
  ON goals
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Users can update own goals"
  ON goals
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = owner_id);

CREATE POLICY "Users can delete own goals"
  ON goals
  FOR DELETE
  TO authenticated
  USING (auth.uid() = owner_id);

-- Create RLS policies for tasks
CREATE POLICY "Users can read own tasks"
  ON tasks
  FOR SELECT
  TO authenticated
  USING (auth.uid() = owner_id);

CREATE POLICY "Users can create own tasks"
  ON tasks
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Users can update own tasks"
  ON tasks
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = owner_id);

CREATE POLICY "Users can delete own tasks"
  ON tasks
  FOR DELETE
  TO authenticated
  USING (auth.uid() = owner_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_goals_owner_id ON goals(owner_id);
CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
CREATE INDEX IF NOT EXISTS idx_tasks_owner_id ON tasks(owner_id);
CREATE INDEX IF NOT EXISTS idx_tasks_goal_id ON tasks(goal_id);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_date ON tasks(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);